export type { Platform, BrowserName, UAParsed } from './browser.js'
export {
  getPlatform,
  isMobile,
  isDesktop,
  isTablet,
  getBrowser,
  getBrowserVersion,
  isWechat,
  isWecom,
  isDingtalk,
  isMiniProgramWebView,
  getScreenWidth,
  getScreenHeight,
  getViewportWidth,
  getViewportHeight,
  getDevicePixelRatio,
  isLandscape,
  isPortrait,
  isRetina,
  isTouchSupported,
  isWebSocketSupported,
  isEventSourceSupported,
  isServiceWorkerSupported,
  isWasmSupported,
  isIntersectionObserverSupported,
  isResizeObserverSupported,
  isLocalStorageSupported,
  isSessionStorageSupported,
  isIndexedDBSupported,
  isWebCryptoSupported,
  isBroadcastChannelSupported,
  isClipboardSupported,
  getConnectionType,
  isOnline,
  isSlowNetwork,
  parseUA,
} from './browser.js'
